import java.util.Scanner;

public class GuesserGame {
	public static void main(String[] args) 
	{
//		
        System.out.println("rule of the game:Three player will play the game.each player will be given  "
		+ "five chances to guess a random number generated by the computer .the player having "
		+ "maximum no of correct guesses will win the game");
int p1Win=game();   

int p2Win=game(); 

int p3Win=game(); 
if (p1Win>p2Win&&p1Win>p3Win) {
	System.out.println("Hurray! player 1 has won the tournamnet with most no of right guesses."+p1Win);
	
}
	
	if (p2Win>p1Win&&p2Win>p3Win) {
		System.out.println("Hurray! player 2 has won the tournamnet with most no of right guesses."+p2Win);
		
	}
		
	else if (p3Win>p2Win&&p3Win>p1Win) {
	System.out.println("Hurray! player 3 has won the tournamnet with most no of right guesses."+p3Win);
	
}
	else if (p3Win==p2Win&&p3Win==p1Win) {
	System.out.println("match has been tied between all the players .");
	
}
	else {
		System.out.println("sorry .no result.");
	}

	
	}
	static int random()
	{
		int randomNumber1=(int)(Math.random()*100);
		return randomNumber1;
	}
	

	static int game() 
	 {

		Scanner sc =new Scanner(System.in);
		System.out.println("new player arrives:");
	     int randomNumber = random();
	     
		int n=1;
		int count=0;
		while (n<=5) 
		{
			System.out.print("guess your chance"+n+":");
			int number=sc.nextInt();
			if (number==randomNumber) 
			{
				System.out.println("u got that right.");
				count++;
				randomNumber = random();
			
				
			}
			else if (number>randomNumber) {
				System.out.println("please enter a number smaller than this number.");
				
			}
			else {
				System.out.println("please enter a larger number than this.");
			}
			n++;
			
		}
		return count;
			
		}
}
